import type { Preset } from './types';

export const PRESETS: Preset[] = [
  {
    id: 'A',
    name: 'Preset A',
    label: 'Compact · 360 × 760',
    deviceWidth: 360,
    deviceHeight: 760,
    screenInset: 6,
    cornerRadius: 38,
    bezelWidth: 10,
    description: 'Dense compact form — small-screen Android-class spacing',
  },
  {
    id: 'B',
    name: 'Preset B',
    label: 'Standard · 390 × 844',
    deviceWidth: 390,
    deviceHeight: 844,
    screenInset: 8,
    cornerRadius: 48,
    bezelWidth: 12,
    description: 'Reference standard — modern flagship-class spacing',
  },
  {
    id: 'C',
    name: 'Preset C',
    label: 'Pro Max · 430 × 932',
    deviceWidth: 430,
    deviceHeight: 932,
    screenInset: 8,
    cornerRadius: 55,
    bezelWidth: 13,
    description: 'Large display — plus-sized flagship with generous viewport',
  },
  {
    id: 'D',
    name: 'Preset D',
    label: 'Tablet · 568 × 932',
    deviceWidth: 568,
    deviceHeight: 932,
    screenInset: 10,
    cornerRadius: 32,
    bezelWidth: 14,
    description: 'Widened aspect — mini-tablet and foldable-landscape class',
  },
  {
    id: 'E',
    name: 'Preset E',
    label: 'Ultra-wide · 600 × 900',
    deviceWidth: 600,
    deviceHeight: 900,
    screenInset: 10,
    cornerRadius: 28,
    bezelWidth: 16,
    description: 'Expansive canvas — tablet-portrait and web-view class',
  },
];
